.roots = (
    "test.ks",
    "src/day01/main.ks",
    "src/day02/main.ks",
    "src/day03/main.ks",
    "src/day04/main.ks",
    "src/day05/main.ks",
    "src/day06/main.ks",
    "src/day07/main.ks",
    "src/day08/main.ks",
    "src/day09/main.ks",
    "src/day10/main.ks",
    "src/day11/main.ks",
    "src/day12/main.ks",
)
